### ISSUE TITLE
Feedback for "Сборка merged-бандла"

### ISSUE THREAD

**Issue by zakaratcha** [enb/enb-bem-techs#205]
Столкнулся с проблемой: сделал примерно как в инструкции https://ru.bem.info/tools/bem/enb-bem-techs/build-merged-bundle/
Когда запускаю через enb make - всё хорошо.
Когда же сборка стартует от enb-сервера, то собирается только показанная страница и merged-бандла не получается.
Не могу допетрить, как это обойти.

**Comment by blond** [comment]
> Когда же сборка стартует от enb-сервера, то собирается только показанная страница и merged-бандла не получается.

А в коде страницы подключается CSS/JS merged-бандла?

**Comment by zakaratcha** [comment]
Не подключался. Спасибо за наводку. Теперь всё гуд)
