### ISSUE TITLE
Feedback for "Как устроены БЭМ-проекты"

### ISSUE THREAD

**Issue by ego-web** [enb/enb-bem-techs#223]
на стр.: https://ru.bem.info/tools/bem/enb-bem-techs/bem-project/
повторение:
── button_type_link.css
── button_type_link.css
возможно имелось ввиду:
── button_type_link.css
── button_type_link.js

**Comment by tadatuta** [comment]
Спасибо! Будет исправлено в следующем обновлении сайта.
