### ISSUE TITLE
use node-eval

### ISSUE THREAD

**Issue by blond** [enb/enb-bem-techs#230]
We can use [node-eval](https://github.com/gulp-bem/node-eval) module instead of `enb-async-require` and `enb-require-or-eval`.

It is possible to decrease memory consumption: require cache is not used.

After the changes we can not substitute techs in tests: https://github.com/enb/enb-bem-techs/blob/master/test/utils/techs.js.

**Comment by skad0** [comment]
Agreed with @Yeti-or and @blond that we should integrate node-eval into enb-require-or-eval.

**Comment by blond** [comment]
Fixed in https://github.com/enb/enb-bem-techs/pull/243
